version: 2

sources:
  - name: fivetran_database
    schema: raw
    tables:
      - name: appointment_airbyte
        identifier: appointment_airbyte
      - name: appointment_fivetran
        identifier: appointment_fivetran
      - name: invoice_fivetran
        identifier: invoice_fivetran
      - name: invoice_airbyte
        identifier: invoice_airbyte
      - name: invoice_items_fivetran
        identifier: invoice_items_fivetran
      - name: invoice_items_airbyte
        identifier: invoice_items_airbyte